### ISSUE TITLE
Demo services down due to Dockerfile problems

### ISSUE THREAD

**Issue by Anson-Zhao** [geopython/pygeoapi#584] opened 2020-12-02 04:26 UTC
Could you please double check the service link below, which is down. Thanks.

https://demo.pygeoapi.io/covid-19/collections/cases/items?f=json&limit=10000

**Comment by justb4** [comment] 2020-12-02 07:42
Think this is caused by PR #582. `itemType` was changed to array but still referred as string e.g. here
https://github.com/geopython/pygeoapi/blob/f4859d6bd66836f0e0a588881ffd48634e23a068/pygeoapi/templates/collection.html#L16
@pvgenuchten can you check?

**Comment by justb4** [comment] 2020-12-02 10:01
Hmm, maybe another reason, seeing this in server log:

```
    from osgeo import gdal as osgeo_gdal
ModuleNotFoundError: No module named 'osgeo'
ERROR: openapi.yml could not be generated ERROR
```
Something changed in GDAL Python bindings installation?

**Comment by justb4** [comment] 2020-12-02 10:19
Also seeing this error after building the latest Docker Image:

```
ModuleNotFoundError: No module named 'pkg_resources'
```

I suspect some kind of silent version upgrade in Debian and/or Python packages , not related to any pygeoapi code.

**Comment by pvgenuchten** [comment] 2020-12-02 11:20
#582 is closed without merge, but i guess you found the issue elsewhere
thanx for checking @justb4

**Comment by justb4** [comment] 2020-12-02 11:50
Appears to be suddenly quite some problems with the Dockerfile build. For one thing the package `python3-gdal` (and others) is auto-removed at cleanup at the end. This was never the case before. See the build logfile attached here. Think having Debian Bullseye-slim as base Image is a moving target....I also see even Python 3.9 installed.

[docker-build.log](https://github.com/geopython/pygeoapi/files/5629032/docker-build.log)

**Comment by justb4** [comment] 2020-12-02 12:19
Ok, latest commit fixed the Dockerfile (and hopefully Travis) build. Demo services should be up again @Anson-Zhao .

**Comment by justb4** [comment] 2021-02-09 10:18
@Anson-Zhao think we can close this?

**Closed** 2021-02-22 20:59 UTC
Labels: bug
