### ISSUE TITLE
Lakes Collection not loading due to provider exception

### ISSUE THREAD

**Issue by jvanulde** [geopython/pygeoapi#769] opened 2021-08-26 18:09 UTC
**Description**
When dereferencing the link to the Lakes collection the following exception is thrown:

```
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'type'
```

**Steps to Reproduce**

1. build local install
2. dereference http://localhost:5000/collections/lakes

**Expected behavior**
Lakes collection should load

**Screenshots/Tracebacks**
```
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'type'

Traceback (most recent call last)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/flask_app.py", line 163, in collections
return get_response(api_.describe_collections(request, collection_id))
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/api.py", line 140, in inner
return func(cls, req_out, *args[2:])
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/linked_data.py", line 57, in inner
return func(*args, **kwargs)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/api.py", line 1042, in describe_collections
content = render_j2_template(self.config,
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/util.py", line 365, in render_j2_template
return template.render(config=l10n.translate_struct(config, locale_, True),
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Jinja2-3.0.1-py3.9.egg/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/Jinja2-3.0.1-py3.9.egg/jinja2/environment.py", line 925, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/templates/collections/collection.html", line 1, in top-level template code
{% extends "_base.html" %}
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/templates/_base.html", line 70, in top-level template code
{% block body %}
File "/Users/nrcan/Sites/pygeoapi/venv/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/templates/collections/collection.html", line 49, in block 'body'
{% if 'tile' in provider['type'] %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'type'
```
**Environment**
 - OS: MacOS
 - Python version: 3.9
 - pygeoapi version: latest

**Comment by tomkralidis** [comment] 2021-09-13 18:50
I think this is rooted in the recent i18n changes.  @GeoSander can you take a look?

**Comment by GeoSander** [comment] 2021-09-15 10:47
Hi @jvanulde, could you please clarify what you mean by "dereference http://localhost:5000/collections/lakes"?
How can I do this _myself_? Afaik this is done by the application? But perhaps I use a different definition than you...

**Comment by jvanulde** [comment] 2021-09-15 19:16
> Hi @jvanulde, could you please clarify what you mean by "dereference http://localhost:5000/collections/lakes"?

Sorry for the wording, I meant click on the link to go to the resource.

**Comment by GeoSander** [comment] 2021-09-16 14:58
Then I understood you correctly 👍 
However, I can't reproduce your error unfortunately... The problem is that I cannot simply run a true local build on my machine, because I'm on Windows and I can't get the rasterio dependency to work (even after I pointed it to the correct GDAL lib and include files), so I am forced to build a local Docker container and run that.
But no matter what I try (click your link above, click on the Lakes link on the http://localhost:5000/collections page, direct request, etc.) I always get to see the lakes collection and no errors show up.
Were you able to reproduce this, @tomkralidis?

**Comment by jvanulde** [comment] 2021-09-16 22:47
@GeoSander curiously, I don't get the error with the Docker container, only with the local build. Ideas on where we can look for the culprit?

**Comment by tomkralidis** [comment] 2021-09-17 01:12
FYI I'm having the same issue against a local build of master.  See minimal config and test case below:

http://localhost:5000/collections/canada-metadata (results in 500, same traceback as @jvanulde)

```yaml
server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages:
        - en-US
        - fr-CA
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    canada-metadata:
        type: collection
        title:
            en: MSC WIS DCPC discovery metadata
            fr: Exemple de donn\u00e9es Canada Ouvert
        description:
            en: MSC WIS DCPC discovery metadarta in support of the WIS 2.0 search pilot project
            fr: Exemples d'enregistrements de m\u00e9tadonn\u00e9es sur ouvert.canada.ca
        keywords:
            en:
                - canada
                - open data
            fr:
                - canada
                - donn\u00e9es ouvertes
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://open.canada.ca/en/open-data
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: information
              href: https://ouvert.canada.ca/fr/donnees-ouvertes
              hreflang: fr-CA
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/open.canada.ca/sample-records.tinydb
              id_field: externalId
              time_field: recordCreated
              title_field: title
```

**Comment by GeoSander** [comment] 2021-09-17 11:49
Very strange... I could try and see if I can succeed in making a local build (perhaps on WSL2) to reproduce.

**Comment by jvanulde** [comment] 2021-09-17 19:37
From my testing it looks like `_translate_dict` in I18n.py is returning malformed dict objects.

**Comment by jvanulde** [comment] 2021-09-17 21:17
It appears that some property keys are resulting in failed translations. For example the `id_field` property in particular is a problem. The translator infers that `id_` is language code. If I ignore that specific key as follows the issue is resolved:

```# Find valid locale keys in language struct
    # Also maps Locale instances to actual key names
    loc_items = OrderedDict()
    for k in value.keys():
        # ignore offending key
        if k == 'id_field':
            continue
        loc = str2locale(k, True)
        if loc:
            loc_items[loc] = k
            
````

**Comment by GeoSander** [comment] 2021-09-18 22:39
Thanks for tracking this down, @jvanulde. I wasn't able to reproduce the issue, but I could reproduce the translation mistake.
So it looks like Tom was right then. It _was_ my fault! ;) 
In my defense though: it seems that Babel's `Locale.parse` accepts pretty much anything as a "territory", even _field_ 😅 
Still strange that this does not occur on a Docker instance. How could this behave differently...? Other Babel versions perhaps?

Anyway, to make it all a bit more robust while keeping it simple, I thought that it would be best to say that a language struct will only be translated if all of the tags (keys) defined in the struct are valid languages/locales. Silly that I didn't do that in the first place...

**Comment by tomkralidis** [comment] 2021-09-19 11:21
#779 merged.

P.S. @GeoSander there is no 'fault' :), thanks to you and @jvanulde both -- great job/teamwork!

**Closed** 2021-09-19 17:24 UTC
Labels: bug
