### ISSUE TITLE
Bad Leaflet bounds in Tiles template

### ISSUE THREAD

**Issue by vidhav** [geopython/pygeoapi#1043] opened 2022-11-24 11:42 UTC
**Description**
In the [HTML template for Tiles](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/collections/tiles/index.html#L131), the Leaflet viewport is set to the bbox of the collection. Leaflet orders the coordinates by latitude-longitude (the bbox uses the opposite order).

**Steps to Reproduce**
Set the collection bbox to be `[4,57,32,72]`. The viewport should place you in the Arabian sea.

**Expected behavior**
Should show all of mainland Norway in the viewport.

**Environment**
 - OS: Windows 10
 - Python version: 3.10.5
 - pygeoapi version: 0.13.0

**Comment by doublebyte1** [comment] 2022-11-27 10:51
@vidhav the order of the coordinates seems to be correct, according to the [Leaflet documentation](https://leafletjs.com/reference.html#latlngbounds).
I think that the problem is that the bounds being passed to this method correspond to the bounds of the extent, rather than the bounds of the actual data (see screenshot).

![pygeoapi-extent](https://user-images.githubusercontent.com/1038897/204131367-cfc22d24-081e-4430-8b0e-2b5bb5d66d5c.png)

**Comment by doublebyte1** [comment] 2022-11-27 11:40
If you set the extent of the layer in the [configuration of pygeoapi](https://github.com/geopython/diving-into-pygeoapi/blob/main/workshop/exercises/pygeoapi.config.yml#L227), the map will be correctly fitted.

![tiles-extent](https://user-images.githubusercontent.com/1038897/204133265-217bd67d-485e-4436-91ba-69508613c5e6.png)

**Comment by doublebyte1** [comment] 2022-11-27 11:44
If one day there is support for getting the bounds of a [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid#todo), we could try to fit the map to the data extent, instead. Maybe @IvanSanchez knows something about this...

**Comment by vidhav** [comment] 2022-11-28 08:23
I did set the extent in the the [config file](https://github.com/geopython/diving-into-pygeoapi/blob/main/workshop/exercises/pygeoapi.config.yml#L227), @doublebyte1. I pass it in as `[west, south, east, north]`, so in my understanding it's `[lng, lat, lng, lat]`...

It is my understanding that Leaflet prefers latitude, longitude and the [documentation](https://leafletjs.com/reference.html#latlngbounds) does state that order quite consistently. However, it looks like `latLngBounds` accepts the corners in any order, so my challenge is the order of latitude and longitude:

```javascript
// Code as is, puts my map in the wrong location:
bounds = L.latLngBounds([[{{ data['bounds'][0] }},{{data['bounds'][1]}}],[{{ data['bounds'][2] }},{{data['bounds'][3]}}]])
// Swapped lons and lats, puts my map in the right position:
bounds = L.latLngBounds([[{{ data['bounds'][1] }},{{data['bounds'][0]}}],[{{ data['bounds'][3] }},{{data['bounds'][2]}}]])
```

I might be missing something obvious as I am more a web developer than I am a GIS developer :)

**Comment by doublebyte1** [comment] 2022-11-28 12:59
@vidhav in the configuration it has: [-180, -90, 180, 90], which would translate to [lat, long,lat,long] (you need to swap your order);  first is the lower left corner and then the upper right corner. If you do this, the current code in the HTML template will put the map in the right location.

**Comment by doublebyte1** [comment] 2022-11-30 15:50
I will close this for the time being. You can reopen it, if the fix does not work.

**Comment by doublebyte1** [comment] 2023-03-06 12:50
@vidhav apologies for taking so long. I opened a PR to fix this, [here](https://github.com/geopython/pygeoapi/pull/1163).

**Comment by doublebyte1** [comment] 2023-03-06 19:48
I'll close this issue, as the PR was merged. @vidhav lthank you for your contribution and et me know, if it does not work as expected

**Closed by doublebyte1** 2023-03-06 19:48 UTC
Labels: bug
