### ISSUE TITLE
Resolver error when accessing items

### ISSUE THREAD

**Issue by jvanulde** [geopython/pygeoapi#334] opened 2020-01-09 20:19 UTC
I get an error:

    Resolver error at paths./collections/obs/items.get.parameters.1.$ref
Could not resolve reference: Failed to fetch

When accessing: https://demo.pygeoapi.io/master/openapi#/obs/get_collections_obs_items

Inline in the Swagger documentation I see the following message:

    Could not render this component, see the console.

<img width="1437" alt="Screen Shot 2020-01-09 at 12 16 39 PM" src="https://user-images.githubusercontent.com/2255248/72101631-023c7f80-32da-11ea-9c69-90a444987a1a.png">

**Comment by tomkralidis** [comment] 2020-01-13 02:17
@jvanulde I'm not able to reproduce on a local install. Not sure if this is a networking error from demo.pygeoapi.io to schemas.opengis.net

**Comment by tomkralidis** [comment] 2020-01-17 18:34
Duplicate of #312

**Closed by tomkralidis** 2020-01-17 18:34 UTC
