### ISSUE TITLE
Working example of /collections/{collectionId}/position 

### ISSUE THREAD

**Issue by esumit** [geopython/pygeoapi#1085] opened 2023-01-03 15:02 UTC
**Describe the solution you'd like**
Working example of /collections/{collectionId}/position

**Comment by francbartoli** [comment] 2023-01-03 15:57
@esumit can you please describe what the issue is and provide more context about it? What OGC API specification are you referring to? Is this a duplicate of #1086?

**Comment by esumit** [comment] 2023-01-03 23:11
@francbartoli Its not a duplicate of #1086 , as #1086 referring to area API of OGC EDR spec, but this is referring to position API of OGC EDR.

**Closed** 2023-01-05 11:37 UTC
Labels: enhancement
